config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users,  :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :questions
  resources :answers
  concern :commentable do
    resources :comments
  end
  resources :questions,concern: :commentable, shallow: true do
    resources :answers do
      resources :comments
    end
    resources :comments, shallow: true
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :all, on: :collection
      end
      resources :questions do
        get '/:id/answers', to: 'questions#answers', on: :collection
        get 'answers/:id', to: 'questions#answer', on: :collection
      end
    end
  end
  root to: "questions#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  attr_reader :user

  def initialize(user)
    @user = user

    if user
      user.admin? ? admin_abilities : user_abilities
    else
      guest_abilities
    end

  end

  def guest_abilities
    can :read, :all
  end
  def admin_abilities
    can :manage, :all
  end
  def user_abilities
    guest_abilities
    can :create, [Question, Answer, Comment]
    can :update, [Question, Answer], user: user
    can :destroy, [Question, Answer], user: user

  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :body, presence: true
  belongs_to :question
  belongs_to :user

  has_many :attachments, as: :attachmentable
  has_many :comments, as: :commentable

  accepts_nested_attributes_for :attachments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachmentable, optional: true
  mount_uploader :file, FileUploader

end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable , optional: true

  validates :body, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, :body, presence: true
  has_many :answers
  has_many :attachments, as: :attachmentable
  has_many :comments, as: :commentable
  belongs_to :user

  accepts_nested_attributes_for :attachments

  after_create :calculate_reputation
 private
  def calculate_reputation
    reputation = Reputation.calculate(self)
    self.user.update(reputation: reputation)
  end



end

app/models/reputation.rb
class Reputation
  def self.calculate(object)

  end
end

app/models/user.rb
class User < ApplicationRecord
  require 'omniauth'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable, :omniauth_providers => [:twitter, :facebook]
  has_many :authorizations
  has_many :answers
  has_many :questions

  def self.find_for_oauth(auth)
    authorization = Authorization.where(provider: auth.provider, uid: auth.uid.to_s).first
    return authorization.user if authorization


    email = auth.info[:email]
    user = User.where(email: email).first
    if user
      user.create_authorization(auth)
    else
      password = Devise.friendly_token[0, 20]
      user = User.create!(email: email, password: password, password_confirmation: password)
      user.create_authorization(auth)
    end
    user
  end

  def create_authorization(auth)
    self.authorizations.create(provider: auth.provider, uid: auth.uid)
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :answer_params, only: :destroy
  before_action :load_answer, only: [:update, :destroy]
  respond_to :js, only: [:create, :destroy]
  authorize_resource
  def create
    @question = Question.find(params[:question_id])
    respond_with(@answer = @question.answers.create(set_params.merge(user_id: current_user.id)))
  end

  def update
    @answer.update(set_params.merge(user_id: current_user.id))
    respond_with @answer
  end
  def destroy
    respond_with @answer.destroy, location: -> {@question}
  end
  private
  def answer_params
    @answer = Answer.find(params[:id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end
  def set_params
    params.require(:answer).permit(:body, :question_id, :user_id, attachments_attributes: [:file])
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  skip_authorization_check
  before_action :doorkeeper_authorize!
  respond_to :json

  protected
  def current_resource_owner
    @current_reource_owner ||= User.find(doorkeeper_token.resource_owner_id) if doorkeeper_token
  end
end

app/controllers/api/v1/profiles_controller.rb
class Api::V1::ProfilesController < Api::V1::BaseController
  def me
    respond_with current_resource_owner
  end
  def all
    @users = User.all
    @users = @users
    respond_with @users
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_collection, only: :index
  before_action :load_question, only: [:show, :answers]
  before_action :load_answer, only: :answer

   def index
     respond_with @questions.to_json
   end
  def show
    respond_with @question
  end

   def answers
     @answers = @question.answers
     respond_with @answers
     end
   def answer
     respond_with @answer
   end
  private
   def load_collection
     @questions = Question.all
   end
  def load_question
    @question = Question.find(params[:id])
    end
  def load_answer
    @answer = Answer.find(params[:id])
   end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  check_authorization :unless => :devise_controller?
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
  respond_to :html, :json

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to questions_path, alert: exception.message
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_parent, only: :create
  respond_to :js
  authorize_resource


  def create
    respond_with(@comment = @parent.comments.create(comment_params))
  end

  private

  def load_parent
    @parent = Question.find(params[:question_id]) if params[:question_id]
    @parent ||= Answer.find(params[:answer_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/omniauth_callbacks_controller.rb
class  OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_oauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebock') if is_navigational_format?
    end
  end
  def twitter
    @user = User.find_for_oauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Twitter') if is_navigational_format?
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :question_params, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :index ]
  before_action :build_answer, only: :show
  authorize_resource
  respond_to :js
  def index
   @question = Question.new
   respond_with(@questions = Question.all)
  end

  def show
  respond_with @question
  end

  def new
  respond_with(@question = Question.new)
  end

  def edit
  end

  def create
    @questions = Question.all
    respond_with(@question = current_user.questions.create(set_params))
  end
  def update
    @question.update(set_params)
    respond_with @question
  end

  def destroy
    respond_with(@question.destroy)
  end

  private

  def build_answer
    @answer = @question.answers.build
    end
  def question_params
    @question = Question.find(params[:id])
  end
  def set_params
    params.require(:question).permit(:title, :body, :user_id, attachments_attributes: [:file])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/create.js.erb
<% publish_to "/questions/#{@question.id}/answers" do %>
  $('.answers').html('<%= j render 'questions/answer' %>' );
  $('.new_answer #answer_body').val('');
<% end %>

app/views/answers/update.js.erb
$('.answers').html('<%= j render 'questions/answer' %>' );
$('.edit-answer-link').click(function(e) {
    e.preventDefault();
    $(this).hide();
    answer_id = $(this).data('answerId');
    $('form#edit-answer-' + answer_id).show();
});

app/views/comments/_comment.html.slim
p= comment.body

app/views/comments/_list.html.slim
= render parent.comments
= form_for [parent, parent.comments.build], remote: true do |f|
  p
    = f.label :body, 'Comment'
    = f.text_area :body
  p
      = f.submit 'Post comment'

app/views/comments/create.js.erb
var parentSelector = '<%= @parent.is_a?(Question) ? ".question" : "#answer-#{@parent.id}" %>';
$(parentSelector + ' .comments').html('<%= j render "list", parent: @parent %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackOverflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="container">
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
     <% if user_signed_in? %>
         <%= link_to 'sign out', destroy_user_session_path, method: :delete%>
         <% if current_user.admin? %>
             <h1>User Admin</h1>
         <% else %>
             <h1>User</h1>
         <% end %>
     <% else %>
         <%= link_to 'log in', new_user_session_path%>
         <%= link_to 'sign in', new_user_registration_path %>
     <% end %>
     <%= render 'shared/head' %>

     <%= yield %>
   </div>
  </body>
</html>

app/views/questions/_answer.html.slim
- @question.answers.each do |answer|
  - if answer.persisted?
    .answer id="answer-#{answer.id}"
      p= answer.body
      #answer_user
        = answer.user.email
      ul
        - answer.attachments.each do |f|
          li= link_to f.file.file.filename, f.file.url
      - if answer.user.id == current_user.id
        - if user_signed_in?
          p= link_to 'destroy', answer, method: :delete
          p= link_to 'Edit', '', class: 'edit-answer-link', data: {answer_id: answer.id}
        = form_for answer, remote: true, html: {id: "edit-answer-#{answer.id}"} do |f|

            = f.label :body, 'Answer'
            = f.text_area :body
            = f.submit 'Save'
        .comments
            = render 'comments/list', parent: answer

app/views/questions/_form.html.slim
= form_for @question, remote: true do |f|
  = f.error_messages
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body
  .submit-create-question= f.submit  action: @question.new_record? ? 'Create' : 'Update'
  p Attachments:
  p
    = f.fields_for :attachments,@question.attachments.build do |a|
      = a.label :file
      = a.file_field :file

app/views/questions/_question.html.slim
#question_title = link_to question.title, question
#question_body = link_to question.body, question
-if user_signed_in?
  - if question.user.id == current_user.id
    #link_edit = link_to 'Edit question', edit_question_path(question)
    #link_destroy_answer = link_to 'Destroy', question, method: :delete, data: {confirm: 'Are you sure?'}



#question_user = question.user.email

app/views/questions/create.js.erb
<% publish_to "/questions" do %>
  $('.questions').html('<%= j  render @questions  %>' );
  $('.new_question #question_body,.new_question #question_title').val('');
<% end %>

app/views/questions/edit.html.slim
= render 'form'

app/views/questions/index.html.slim
.link_new
  p= link_to 'Ask question', new_question_path

.questions
  = render @questions


.new_question_create
  = render 'form'
= subscribe_to "/questions"

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
.question
  h1 show question
  strong = @question.title
  br
  strong = @question.body
  br
  strong = @question.user.email
  - if @question.attachments.present?
    p Attachment:
      ul
        - @question.attachments.each do |f|
          li= link_to f.file.file.filename, f.file.url
  .comments
    = render 'comments/list', parent: @question


.answers data={question_id: "#{@question.id}"}
  = render 'answer'
br
= form_for [@question, @answer], remote: true do |f|
  = f.label :body, 'You answer'
  = f.text_area :body
  = f.submit 'Create'
  p
    = f.fields_for :attachments, @answer.attachments.build  do |a|
      = a.label :file
      = a.file_field :file
    p = f.submit 'Save'


br

= link_to 'add answer', new_question_answer_path(@question)
= subscribe_to "/questions/#{@question.id}/answers"

app/views/shared/_head.html.slim
nav.navbar.navbar-dark.bg-inverse
  a.navbar-brand href="asd" lalala
  ul class="nav navbar-nav"
    li class="nav-item active"
      a class="nav-link" href="#" Home
      span class="sr-only" (current)